name: Run Robot Framework Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # สามารถ run workflow ได้ด้วยตนเองจาก GitHub UI

jobs:
  test:
    runs-on: ubuntu-latest  # ใช้ Ubuntu เป็น runner
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # ดึงโค้ดจาก repo

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # กำหนดเวอร์ชันของ Python

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          # Install additional dependencies if needed
          pip install -r requirements.txt

      - name: Run Robot Framework Tests
        run: |
          robot --dryrun -d results tests/  # รันไฟล์ที่อยู่ในโฟลเดอร์ tests และเก็บผลลัพธ์ในโฟลเดอร์ results
        continue-on-error: true

      - name: Upload Test Results
        if: always()  # อัปโหลดผลลัพธ์ไม่ว่าจะผ่านหรือล้มเหลว
        uses: actions/upload-artifact@v4
        with:
          name: robot-results
          path: ./results